<a href="https://colab.research.google.com/github/Kvaibhav1997/Customer_data/blob/main/Customer_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [90]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [27]:
from google.colab import files
uploaded=files.upload()

In [53]:
df=pd.read_csv("customer-data.csv")

In [54]:
df.head()

id    age  gender  ... DUIs past_accidents outcome
0  569520    65+  female  ...    0              0   False
1  750365  16-25    male  ...    0              0    True
2  199901  16-25  female  ...    0              0   False
3  478866  16-25    male  ...    0              0   False
4  731664  26-39    male  ...    0              1    True

[5 rows x 19 columns]

In [55]:
df.drop(['id', 'postal_code'], axis=1,inplace=True)

In [56]:
#Q1. What proportion of customers with a credit score below 0.2 made a claim in the last year?
data1=df[df['credit_score']>0.2].value_counts()
print(data1)

age    gender  race      driving_experience  education    income         credit_score  vehicle_ownership  vehicle_year  married  children  annual_mileage  vehicle_type  speeding_violations  DUIs  past_accidents  outcome
65+    male    minority  30y+                university   upper class    0.746672      True               after 2015    False    True      17000.0         sedan         1                    1     2               False      1
26-39  female  minority  10-19y              high school  middle class   0.547843      True               before 2015   False    False     15000.0         sedan         0                    0     1               True       1
                         0-9y                none         working class  0.661762      False              before 2015   False    False     12000.0         sedan         0                    0     0               True       1
                                             university   middle class   0.535840      True              

In [57]:
#Q2. What is the average number of speeding violations among customers with driving experience between 20 and 29 years (inclusive)?
data2=df[df['driving_experience']=='20-29y']

print("The average no. of speeding violation is % s."% data2['speeding_violations'].mean())

The average no. of speeding violation is 2.734308636149127.


In [58]:
#Q3. What if you consider only the people in this group who drive a sports car?
sports_car_driver=df[df['vehicle_type']=='sports car']
print(sports_car_driver)

        age  gender      race  ... DUIs past_accidents outcome
25    26-39  female  majority  ...    0              0   False
38      65+    male  majority  ...    0              5   False
45    40-64    male  majority  ...    0              4   False
89    16-25    male  majority  ...    0              0    True
113   16-25    male  majority  ...    0              0    True
...     ...     ...       ...  ...  ...            ...     ...
9884  26-39  female  majority  ...    0              0    True
9932  16-25  female  majority  ...    0              0   False
9943    65+    male  majority  ...    0              5   False
9958  40-64    male  majority  ...    2              4   False
9972  26-39  female  majority  ...    0              1   False

[477 rows x 17 columns]


In [59]:
#Q4. What is the standard deviation in annual mileage?
print("Standard Deviation of Annual Mileage is % s "% (np.std(df['annual_mileage'])))

Standard Deviation of Annual Mileage is 2818.278688843016 


In [60]:
df.shape

(10000, 17)

In [61]:
df.isnull().sum()

age                      0
gender                   0
race                     0
driving_experience       0
education                0
income                   0
credit_score           982
vehicle_ownership        0
vehicle_year             0
married                  0
children                 0
annual_mileage         957
vehicle_type             0
speeding_violations      0
DUIs                     0
past_accidents           0
outcome                  0
dtype: int64

In [62]:
df.dropna(axis=0, inplace=True)

In [63]:
le=LabelEncoder()

In [64]:
df.dtypes

age                     object
gender                  object
race                    object
driving_experience      object
education               object
income                  object
credit_score           float64
vehicle_ownership         bool
vehicle_year            object
married                   bool
children                  bool
annual_mileage         float64
vehicle_type            object
speeding_violations      int64
DUIs                     int64
past_accidents           int64
outcome                   bool
dtype: object

In [65]:
df['age']=le.fit_transform(df['age'])
df['gender']=le.fit_transform(df['gender'])
df['race']=le.fit_transform(df['race'])
df['driving_experience']=le.fit_transform(df['driving_experience'])
df['education']=le.fit_transform(df['education'])
df['income']=le.fit_transform(df['income'])
df['vehicle_year']=le.fit_transform(df['vehicle_year'])
df['vehicle_type']=le.fit_transform(df['vehicle_type'])

In [66]:
df['children'].replace({True:1,False:0}, inplace=True)
df['married'].replace({True:1,False:0}, inplace=True)
df['outcome'].replace({True:1,False:0}, inplace=True)
df['vehicle_ownership'].replace({True:1,False:0}, inplace=True)

In [67]:
x=df.drop(['outcome'], axis=1)
y=df['outcome']

In [68]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y, test_size=0.2)

#RANDOM FOREST CLASSIFIER

In [69]:
#RANDOM FOREST CLASSIFIER
rfc=RandomForestClassifier(n_estimators=49)

In [70]:
rfc.fit(xtrain,ytrain)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=49,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [71]:
ypred=rfc.predict(xtest)

In [72]:
print("Classification Report is:\n",classification_report(ytest,ypred))
print("Confusion Matrix:\n",confusion_matrix(ytest,ypred))
print("Training Score:\n",rfc.score(xtrain,ytrain)*100)
print("Root Mean Squared Error:\n",sqrt(mean_squared_error(ytest,ypred)))
print("R2 score is:\n",r2_score(ytest,ypred))

Classification Report is:
               precision    recall  f1-score   support

           0       0.86      0.89      0.88      1128
           1       0.74      0.68      0.71       502

    accuracy                           0.83      1630
   macro avg       0.80      0.78      0.79      1630
weighted avg       0.82      0.83      0.82      1630

Confusion Matrix:
 [[1008  120]
 [ 163  339]]
Training Score:
 99.93864089584292
Root Mean Squared Error:
 0.4166768914900855
R2 score is:
 0.1853684552569863


In [73]:
acc=accuracy_score(ytest,ypred)
acc

0.8263803680981595

#KNeighbour CLassifier

In [81]:
#KNeighbour CLassifier
knn=KNeighborsClassifier(n_neighbors=30, metric='minkowski', p=2)
knn.fit(xtrain,ytrain)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=30, p=2,
                     weights='uniform')

In [82]:
ypred1=knn.predict(xtest)

In [83]:
cm= confusion_matrix(ytest, ypred1)  
cm

array([[993, 135],
       [204, 298]])

In [84]:
sqrt(mean_squared_error(ytest,ypred1))
print(knn.score(xtrain,ytrain)*100)

81.14741524773738


In [85]:
acc=accuracy_score(ytest,ypred1)
acc

0.7920245398773006

In [89]:
print("Classification Report is:\n",classification_report(ytest,ypred1))
print("Confusion Matrix:\n",confusion_matrix(ytest,ypred1))
print("Training Score:\n",rfc.score(xtrain,ytrain)*100)
print("Root Mean Squared Error:\n",sqrt(mean_squared_error(ytest,ypred1)))
print("R2 score is:\n",r2_score(ytest,ypred1))

Classification Report is:
               precision    recall  f1-score   support

           0       0.83      0.88      0.85      1128
           1       0.69      0.59      0.64       502

    accuracy                           0.79      1630
   macro avg       0.76      0.74      0.75      1630
weighted avg       0.79      0.79      0.79      1630

Confusion Matrix:
 [[993 135]
 [204 298]]
Training Score:
 99.93864089584292
Root Mean Squared Error:
 0.4560432656258607
R2 score is:
 0.02416928032550658
